services:
- type: web
  name: uml-hybrid
  env: python
  rootDir: backend
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT
